name: checking the expression
on: [push]
env:
  name: orange
jobs:
  expression:
    runs-on: ubuntu-latest
    steps:
      - name: expression
        run: echo "access the expression ${{ env.name }}" 
      - name: check the run id
        run: echo "check the urun id $GITHUB_RUN_ID" 
      - name: default working directory
        run: echo "check for the to working directory $GITHUB_WORKSPACE"      
