name: test
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: first_job
        run: "echo first stage1"
  job2:
    needs: job
    runs-on: ubuntu-latest
    steps:
      - name: second_job
        run: "echo seconf job" 
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: third job
        run: "echo third job"      
         
    
